### ISSUE TITLE
Partials with Parameters Result Ordering Incorrect

### ISSUE THREAD

**Issue by johnhowes** [lynx-json/lynx-docs#108]
Consider the following partial (`name-input.partial.yml`):

```yaml
">list":
  label>~: Name
  input>line:
    spec.input~: name
    value~: ""
```

When I call the partial from a template, like this:

```yaml
">name-input":
  label>: First Name
  spec.input: firstName
  value: John
```

I would expect the resulting document to have a list with a label, followed by an input, but instead I get this (notice that the children are out of order):

```json
{
   "realm":"/",
   "spec":{
      "hints":[
         "list",
         "container"
      ],
      "children":[
         {
            "name":"input"
         },
         {
            "name":"label"
         }
      ]
   },
   "value":{
      "input":{
         "spec":{
            "hints":[
               "line",
               "text"
            ],
            "input":"firstName"
         },
         "value":"John"
      },
      "label":{
         "spec":{
            "hints":[
               "label",
               "text"
            ]
         },
         "value":"First Name"
      }
   }
}
```

**Comment by ansongoldade** [comment]
What is the expectation of calling the partial described in the following scenario?

```
">name-input"
  label: First Name
  spec.input: firstName
  value: John
```

The reason I ask is because of the partial reference in `label>~` that you are using as a placeholder. Is it expected in this scenario that it would
1. Not match the `label>~' placeholder because the keys aren't the same (`label` !== `label>`)
2. Match the `label>~` placeholder and only replace the value
3. Match the `label>~` placeholder and replace the entire key, removing the partial reference.
4. Some other outcome

The current implementation is not considering partial references when matching parameter keys against partials keys. Meaning that right now `label>~: Name` in the partial is not being replaced by `label>: First Name` in the parameter set. I think that is clearly a problem, but I want to understand your thoughts related to the scenario above because that will dictate what logic change needs to be implemented.

**Comment by johnhowes** [comment]
The original implementation matched parameters to placeholders based on the key name, independent of any data-binding or partial metadata in the key. The key name is `label` for all of the following: `label`, `label>`, `label<`, `label=`, `label>~`, `label<>~`, and so on.
