### ISSUE TITLE
Relative url resolution should include `context`.

### ISSUE THREAD

**Issue by ansongoldade** [lynx-json/lynx-docs#114]
When the value for keys `scope`, `realm`, and `for` are relative URIs in the template content they are resolved to absolute values at template processing time. It seems to me that we should also be doing this for `context`. Does anybody recall if there was a conscious decision not to do that?

**Comment by danmork** [comment]
I don't recall, but I doubt the omission was conscious and intentional. I have no objections to `lynx-docs` attempting to resolve it relative to the template's `realm`.

However, after the change to `jsua-lynx` to consider a view to be out of context when its origin view is in a detached state, I wonder how much value the `context` property now has.

**Comment by ansongoldade** [comment]
Sounds like a better solution to the problem that `context` was supposed to solve. I'm going to close this issue.
