### ISSUE TITLE
Consider allowing partials to have pseudo extension.

### ISSUE THREAD

**Issue by ansongoldade** [lynx-json/lynx-docs#40]
We already have knowledge of folders called `_partials` built into lynx-docs so having that knowledge shared with `export` and `start` doesn't seem like a bad thing. Having the same pseudo extension for templates and partials makes it easier to find and refactor template content. Right now in order to find template only content (templates and partials) we have to use a file pattern like `*.yml, !**/*.data/*.yml, !**/*.data.yml`. Think it would be a better experience to use `*.lynx.yml` as the pattern to search across template content.

**Comment by danmork** [comment]
The purpose of a file extension is to indicate the contents of the file. Template content is not equal to partial content. They have different syntax. For example, the keys `spec.hints~` and `*~` have no meaning in a template, but they have meaning in a partial. Since they don't share the same content, it makes sense they don't share the same file pseudo-extension.

Currently, any file in a `_partials` folder is considered to contain partials content (YML or JS). We'd need to retain that for backwards compatibility. However, I'd be in favor of expanding lynx-docs to support an alternative pseudo-extension naming convention for YML and JS partials, e.g. `*.partial.yml` and `*.partial.js`. If we added resolver support for that, then we could put partials in whatever folder we wanted (e.g. next to the template where it is used).

**Comment by ansongoldade** [comment]
Dan and I spoke about this last night. This is an attempt to summarize the outcome of that discussion.

If we think of the 3 aspects of the templating language (template, data, partial) then it becomes natural to think of the following pseudo extensions `*.template.yml`, `*.data.yml|js|json`, and `*.partial.yml|js|json`. 

Given our current state and the fact that backwards compatibility is a requirement, my understanding of the changes would be.
- Add support for `*.template.yml`. With this change `*.lynx.yml` and `*.template.yml` would be the two extensions used for authoring templates.
- Add support for resolving partials that are named `*.partial.yml`. With this change `*.partial.yml` and a directory named `_partials` containing `*.yml|js|json` files would be the two methods for creating partials.

**Comment by johnhowes** [comment]
I'm in favor of the changes.
