### ISSUE TITLE
Missing Content-Length HTTP Header

### ISSUE THREAD

**Issue by danmork** [lynx-json/lynx-docs#57]
The `serveVariant` request handler is not writing a `Content-Length` header to the response. I have not checked other request handlers to see if they also omit the header.

**Comment by ansongoldade** [comment]
Dan,

Here is a typical response I get back from the `serveVariant` handler.
```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:3000
Access-Control-Expose-Headers:X-Variant-Index
Cache-control:no-cache
Connection:keep-alive
Content-Type:application/lynx+json
Date:Sat, 01 Jul 2017 09:58:49 GMT
Transfer-Encoding:chunked
```
Notice the `Transfer-Encoding` header value. According to some articles I've read, when `Transfer-Encoding` is `chunked` the `Content-Length` header is ommitted and each chunk indicates it's length to the browser.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

Let me know if you are seeing the same thing. If it's useful to disable `chunked` encoding so that we can see the `Content-Length` in the headers, then I'll research changing that configuration in express.

**Comment by danmork** [comment]
I missed that. That explains it. I don't think this is an issue then.
